var historique=[];function enregister(){var nomCommune=document.getElementById("commune").textContent;var codeCommune=document.getElementById("infos").textContent;var codeDep=document.getElementById("infosdepartement").textContent;var codeReg=document.getElementById("infosregion").textContent;var administratif=document.getElementById("competenceadmincom").textContent;var numerique=document.getElementById("capaciteusagecom").textContent;var info=document.getElementById("accesinfocom").textContent;var interface=document.getElementById("accesinterfacecom").textContent;genPDF(nomCommune,codeCommune,codeDep,codeReg,administratif,numerique,info,interface);}
function getRegionsData(arg){indiceregion.forEach(indiceregion=>{if(indiceregion.numRegion==arg){document.getElementById("boxreg").style.visibility="visible";document.getElementById("region").innerHTML=indiceregion.Nom;document.getElementById("infosregion").innerHTML=Math.round(indiceregion.SCORE_GLOBAL_REGION);document.getElementById("accesinforeg").innerHTML=Math.round(indiceregion.ACCES_A_INFORMATION);document.getElementById("accesinterfacereg").innerHTML=Math.round(indiceregion.ACCES_AUX_INTERFACES_NUMERIQUES);document.getElementById("capaciteusagereg").innerHTML=Math.round(indiceregion.COMPETENCES_NUMERIQUES_SCOLAIRES);document.getElementById("competenceadminreg").innerHTML=Math.round(indiceregion.COMPETENCES_ADMINISTATIVES);}})
function sendregionsdata(arg){$.ajax({url:"/index.html",type:"POST",data:JSON.stringify({x:xc,y:yc}),contentType:"application/json; charset=utf-8",success:function(dat){console.log(dat);}});}}
function getDepartementData(arg){indicedepartement.forEach(indicedepartement=>{if(indicedepartement.numero==arg){document.getElementById("boxdep").style.visibility="visible";document.getElementById("departement").innerHTML=indicedepartement.Nom;document.getElementById("infosdepartement").innerHTML=Math.round(indicedepartement.Moy_Dep);document.getElementById("accesinfodep").innerHTML=Math.round(indicedepartement.ACCES_A_INFORMATION);document.getElementById("accesinterfacedep").innerHTML=Math.round(indicedepartement.ACCES_AUX_INTERFACES_NUMERIQUES);document.getElementById("capaciteusagedep").innerHTML=Math.round(indicedepartement.COMPETENCES_NUMERIQUES_SCOLAIRES);document.getElementById("competenceadmindep").innerHTML=Math.round(indicedepartement.COMPETENCES_ADMINISTATIVES);}})}
function getCommuneData(arg){data.forEach(data=>{if(data.Code_Iris==arg){document.getElementById("commune").innerHTML=data.commune+" ( "+data.Libelle_Iris+" ) ";document.getElementById("infos").innerHTML=Math.round(data.SCORE_GLOBAL_commune);document.getElementById("accesinfocom").innerHTML=Math.round(data.INFORMATION);document.getElementById("accesinterfacecom").innerHTML=Math.round(data.INTERFACES);document.getElementById("capaciteusagecom").innerHTML=Math.round(data.NUMÉRIQUES);document.getElementById("competenceadmincom").innerHTML=Math.round(data.ADMINISTATIVES);ajouterhisto(data.commune,data.Libelle_Iris,data.SCORE_GLOBAL_commune,data.INFORMATION,data.INTERFACES,data.NUMÉRIQUES,data.ADMINISTATIVES);if(data.SCORE_GLOBAL_commune<=70){document.getElementById("phraseDesc").innerHTML="La commune "+data.commune+" a un indice de fragilité faible et se trouve en partie en exclusion numérique ("+data.SCORE_GLOBAL_commune+").";}else if(data.SCORE_GLOBAL_commune>70&&data.SCORE_GLOBAL_commune<=100){document.getElementById("phraseDesc").innerHTML="La commune "+data.commune+" a un indice de fragilité correct et n'est pas en situation d'exclusion numérique ("+data.SCORE_GLOBAL_commune+").";}else{document.getElementById("phraseDesc").innerHTML="La commune "+data.commune+" a un très bon indice de fragilité numérique ("+data.SCORE_GLOBAL_commune+").";}}})}
var depcode;function recupe(){depcode=document.getElementById("listdepartements").options[document.getElementById("listdepartements").selectedIndex].value;document.getElementById("boxdep").style.visibility="visible";document.getElementById("listcommune").innerHTML="<option value=''>Selectionnez une commune </option>";data.forEach(data=>{if(data.numDepartement==depcode){const $opt=document.createElement("option");$opt.value=data.Code_Iris;$opt.textContent=data.commune+" ( "+data.Libelle_Iris+")";document.getElementById("listcommune").appendChild($opt);}})
getDepartementData(depcode);};function recupinfocommune(){var codeiris=document.getElementById("listcommune").options[document.getElementById("listcommune").selectedIndex].value;document.getElementById("boxcom").style.visibility="visible";var titre=document.getElementById("commune");var infos=document.getElementById("infos");getCommuneData(codeiris);}
function recupinfosregion(){var coderegion=document.getElementById("listregions").options[document.getElementById("listregions").selectedIndex].value;console.log(coderegion);document.getElementById("boxreg").style.visibility="visible";document.getElementById("listdepartements").innerHTML="<option value=''>Selectionnez un département</option>";indicedepartement.forEach(indicedepartement=>{if(indicedepartement.NumeroRegion==coderegion){const $opt=document.createElement("option");$opt.value=indicedepartement.numero;$opt.textContent=indicedepartement.Nom;document.getElementById("listdepartements").appendChild($opt);}})
getRegionsData(coderegion);}
function afficherInfoCommune(){var codeiris=document.getElementById("recherchecommune").options[document.getElementById("recherchecommune").selectedIndex].value;document.getElementById("boxcom").style.visibility="visible";var region;var dep;data.forEach(data=>{if(data.Code_Iris==codeiris){region=data.numRegion;dep=data.numDepartement;}})
getCommuneData(codeiris);getDepartementData(dep);getRegionsData(region);}
function rechercher(){var choix=document.getElementById("choixCodePostal").value;var liste=document.getElementById("recherchecommune");console.log(choix);document.getElementById("recherchecommune").innerHTML="<option value=''>Selectionnez une commune</option>";code.forEach(code=>{if(code.Code_postal==choix){var codecorrespondance=code.Code_commune_INSEE;console.log(codecorrespondance);data.forEach(data=>{if(data.Code_commune==codecorrespondance){console.log(codecorrespondance);const $opt=document.createElement("option");$opt.value=data.Code_Iris;console.log(data.Code_Iris);$opt.textContent=data.commune+" ( "+data.Libelle_Iris+")";console.log(data.commune);liste.appendChild($opt);}})}})}
function ajouterhisto(nom,labeliris,score,info,interface,numerique,administratif){let element={"commune":nom,"label":labeliris,"score":score,"info":info,"interface":interface,"numerique":numerique,"administratif":administratif}
historique.push(element);var table=document.getElementById("histo");var row=table.insertRow();var cell1=row.insertCell(0);var cell2=row.insertCell(1);var cell3=row.insertCell(2);var cell4=row.insertCell(3);var cell5=row.insertCell(4);var cell6=row.insertCell(5);var cell7=row.insertCell(6);cell1.innerHTML=element.commune;cell2.innerHTML=element.label;cell3.innerHTML=element.score;cell4.innerHTML=element.info;cell5.innerHTML=element.interface;cell6.innerHTML=element.numerique;cell7.innerHTML=element.administratif;}
var modal=document.getElementById("myModal");var span=document.getElementsByClassName("close")[0];span.onclick=function(){modal.style.display="none";}
btnDelete.onclick=function(){modal.style.display="none";}